[project]
name = "svg2regs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmsis-svd==0.4",
    "lxml>=6.0.0",
    "pydentifier==0.1.3",
    "setuptools>=80.9.0",
    "six==1.17.0",
]

